name: PR Checks

on:
  pull_request:
    branches-ignore:
      - 'renovate/**'

jobs:
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Lint Tests
        run: npm run lint:tests

  build-and-test:
    name: 'Build and Test - Node ${{ matrix.node }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 15]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node }}

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm test
